var jwt = require('jsonwebtoken')

var token = "eyJhbGciOiJIUzI1NiJ9.IkNhbGwgbWUgSXNobWFlbC4gU29tZSB5ZWFycyBhZ2_igJRuZXZlciBtaW5kIGhvdyBsb25nIHByZWNpc2VseeKAlGhhdmluZyBsaXR0bGUgb3Igbm8gbW9uZXkgaW4gbXkgcHVyc2UsIGFuZCBub3RoaW5nIHBhcnRpY3VsYXIgdG8gaW50ZXJlc3QgbWUgb24gc2hvcmUsIEkgdGhvdWdodCBJIHdvdWxkIHNhaWwgYWJvdXQgYSBsaXR0bGUgYW5kIHNlZSB0aGUgd2F0ZXJ5IHBhcnQgb2YgdGhlIHdvcmxkLiBJdCBpcyBhIHdheSBJIGhhdmUgb2YgZHJpdmluZyBvZmYgdGhlIHNwbGVlbiBhbmQgcmVndWxhdGluZyB0aGUgY2lyY3VsYXRpb24uIFdoZW5ldmVyIEkgZmluZCBteXNlbGYgZ3Jvd2luZyBncmltIGFib3V0IHRoZSBtb3V0aDsgd2hlbmV2ZXIgaXQgaXMgYSBkYW1wLCBkcml6emx5IE5vdmVtYmVyIGluIG15IHNvdWw7IHdoZW5ldmVyIEkgZmluZCBteXNlbGYgaW52b2x1bnRhcmlseSBwYXVzaW5nIGJlZm9yZSBjb2ZmaW4gd2FyZWhvdXNlcywgYW5kIGJyaW5naW5nIHVwIHRoZSByZWFyIG9mIGV2ZXJ5IGZ1bmVyYWwgSSBtZWV0OyBhbmQgZXNwZWNpYWxseSB3aGVuZXZlciBteSBoeXBvcyBnZXQgc3VjaCBhbiB1cHBlciBoYW5kIG9mIG1lLCB0aGF0IGl0IHJlcXVpcmVzIGEgc3Ryb25nIG1vcmFsIHByaW5jaXBsZSB0byBwcmV2ZW50IG1lIGZyb20gZGVsaWJlcmF0ZWx5IHN0ZXBwaW5nIGludG8gdGhlIHN0cmVldCwgYW5kIG1ldGhvZGljYWxseSBrbm9ja2luZyBwZW9wbGUncyBoYXRzIG9mZuKAlHRoZW4sIEkgYWNjb3VudCBpdCBoaWdoIHRpbWUgdG8gZ2V0IHRvIHNlYSBhcyBzb29uIGFzIEkgY2FuLiBUaGlzIGlzIG15IHN1YnN0aXR1dGUgZm9yIHBpc3RvbCBhbmQgYmFsbC4gV2l0aCBhIHBoaWxvc29waGljYWwgZmxvdXJpc2ggQ2F0byB0aHJvd3MgaGltc2VsZiB1cG9uIGhpcyBzd29yZDsgSSBxdWlldGx5IHRha2UgdG8gdGhlIHNoaXAuIFRoZXJlIGlzIG5vdGhpbmcgc3VycHJpc2luZyBpbiB0aGlzLiBJZiB0aGV5IGJ1dCBrbmV3IGl0LCBhbG1vc3QgYWxsIG1lbiBpbiB0aGVpciBkZWdyZWUsIHNvbWUgdGltZSBvciBvdGhlciwgY2hlcmlzaCB2ZXJ5IG5lYXJseSB0aGUgc2FtZSBmZWVsaW5ncyB0b3dhcmRzIHRoZSBvY2VhbiB3aXRoIG1lLiI.6pMf6BlJ6JL-hFr3B9aA6QNoxkIELTH5AExzGRIxHoI"
var secret = 'galvanize_rocks!'
var options = {}

jwt.verify(token, secret, options, verifyToken)

function verifyToken(err,decoded){
  console.log(decoded)
}
